### ISSUE TITLE
[MMP] Recipient fading cannot be overridden by userstyles

### ISSUE THREAD

**Issue by TheEnigmaBlade** [creesch/reddit-moderator-toolbox#414]
Should be moved into a separate stylesheet with new classes added to the elements, like `.recipient` or something.

I know it's currently set as a per-element style with `!important` to override RES and RES nightmode, but overriding can be done in stylesheets with `!important` as well. It just needs a sufficiently long selector.

**Comment by creesch** [comment]
recipient fading can be turned off...

**Comment by TheEnigmaBlade** [comment]
That wasn't my point, but I already fixed it with 96d3ddd8c8607555892d3af9fddd750f30c75162.

**Comment by creesch** [comment]
Alright, fair enough. 

For future reference I attached a .mod-toolbox class to the body and use that for most toolbox related things. 
In modmail it shouldn't be much of an issue but I did that to prevent subreddit css accidentally overwritting toolbox css which did happen in the past. Although in 99% of the cases the tb- prefix should do it.

**Comment by TheEnigmaBlade** [comment]
Yeah, the reason it's not included is because some features have their own class added by MMP. I originally had the CSS use both classes, but then removed it for optimization purposes.

**Comment by creesch** [comment]
Hrm seems you broke it though. RES backgrounds still get applied...

**Comment by agentlame** [comment]
This issue might also be my fault.  It worked correctly before I asked that styles be added *before* init.

**Comment by creesch** [comment]
fixed it c13817f69c98d6cdb683e1187a02ff2743435844
